# Generated by Django 5.2 on 2025-04-26 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='notification_minutes_before',
            field=models.PositiveIntegerField(default=60),
        ),
    ]
